# Generated by Django 5.2.4 on 2025-08-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_couple_is_active_groupe_is_active_membre_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmeeglise',
            name='date_debut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programmeeglise',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
