# Generated by Django 5.2.4 on 2025-08-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_programmeeglise_date_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmeeglise',
            name='heure_debut',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programmeeglise',
            name='heure_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programmeeglise',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programmeeglise',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
