# Generated by Django 5.2.4 on 2025-08-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_programmeeglise_heure_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmeeglise',
            name='recurrence',
            field=models.CharField(choices=[('none', 'Pas de répétition'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel')], default='none', max_length=10, verbose_name='Récurrence'),
        ),
    ]
